modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "https://github.com/Yedelo/ClientSideHurtAnimations/issues"

[[mods]]
modId = "clientsidehurtanimations"
version = "${version}"
displayName = "ClientSideHurtAnimations"
description = "Adds client-side hurt animations when attacking entities"
logoFile = "assets/clientsidehurtanimations/clientsidehurtanimations.png"
logoBlur = false
authors = "Yedel"
displayURL = "https://modrinth.com/mod/clientsidehurtanimations/"

[[mixins]]
config = "clientsidehurtanimations.mixins.json5"

[features.clientsidehurtanimations]
javaVersion = "${java}"

[[dependencies.clientsidehurtanimations]]
modId = "neoforge"
versionRange = "${neoforge}"

[[dependencies.clientsidehurtanimations]]
modId = "minecraft"
versionRange = "${minecraft}"

[[dependencies.clientsidehurtanimations]]
modId = "yet_another_config_lib_v3"
versionRange = "${yacl}"
